#!/usr/bin/python3
class player:
	race="Human"
	HP=100
	AP=10
	DP=10
	MP=5
myplayer=player()#tarif yek nemune
print (myplayer.HP)#print az HP Player
myplayer.HP=myplayer.HP+10 #ezafe kardan 10 HP be Player
print(myplayer.HP)
