#! /usr/bin/python3

class player:
    def __init__ (self):
        self.level=1
        self.hp=100 
    def __str__ (self):
        return ('this is a {}'.format(self.race))
    def levelup(self):
        self.level+=1
        self.hp+=10
class human(player):
    def __init__ (self):
        player. __init__ (self)
        self.hp=200
class elf(player):
    def levelup(self):
        player.levelup(self)
        self.level +=1
        self.hp +=5
class superH(human,elf):
    pass
ali = human()
mamad = elf()
reza = superH()
print("health point reza ",reza.hp)
print("level reza ",reza.level)
reza.levelup()
print("level reza ",reza.level)
print("health point reza ",reza.hp)
print("health point reza ",mamad.hp)
mamad.levelup()
print("level mamad ",mamad.level)
print("health point mamad ",mamad.hp)
print("health point ali ",ali.hp)
ali.levelup()
print("health point ali ",ali.hp)
