#! /usr/bin/python3

dars=["math","physics","farsi"]
daneshjo=["ali","reza","mahdi"]
nomarat=[]
for i in range(len(daneshjo)):
    for j in range(len(dars)):
        a=int(input("{} score {}?".format(dars[j],daneshjo[i])))
        nomarat.append(a)
#print(nomarat)
for i in range(len(dars)):
    print ("mean {} score = ".format(dars[i]),((nomarat[0+i]+nomarat[3+i]+nomarat[6+i])/3))
for j in range(len(daneshjo)):
    print ("total average {} = ".format(daneshjo[j]),((nomarat[0+i*3]+nomarat[1+i*3]+nomarat[2+i*3])/3))
#tamam tamam
