#!/usr/bin/python3
#Player{race , type , weapon , ...}
class player:
	def __init__(self,race): 
		self.level=1
		self.race=race
		if self.race=='Human':
			self.HP=110
		else:
			self.HP=100
	def __str__(self):
		return('This is a {}'.format(self.race))
Ali=player('Human')
print(Ali.HP)
Zahra=player('Elf')
print(Zahra.HP)
print(Ali)
print(Zahra)

	
