#!/usr/bin/python3
#Player{race , type , weapon , ...}
class player:
	def __init__(self): 
		self.level=1
		self.HP=100
	def levelup(self):
		self.level+=1
		self.HP+=10
class Human(player):
	def __init__(self):
		player.__init__(self)
		self.HP=110
class Elf(player):
	def levelup(self):
		self.level+=1
		self.HP+=15
Ali=Human()
print(Ali.HP)
print(Ali.level)
Zahra=Elf()
print(Zahra.level)
print(Zahra.HP)

Zahra.levelup()
print(Zahra.level)
print(Zahra.HP)
